"""migrationn

Revision ID: 061863599e1d
Revises: 37a37df20b4d
Create Date: 2023-11-27 12:25:09.088481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061863599e1d'
down_revision = '37a37df20b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phoneNumber', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Boolean(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup')
    # ### end Alembic commands ###
