"""migrationn

Revision ID: 108cccb69054
Revises: 709ce5fc3b4e
Create Date: 2023-11-27 17:31:46.860705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108cccb69054'
down_revision = '709ce5fc3b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('writer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blog', sa.Text(), nullable=True))
        batch_op.drop_column('Blog')
        batch_op.drop_column('Writer')
        batch_op.drop_column('Title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Writer', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Blog', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('blog')
        batch_op.drop_column('writer')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
