"""empty message

Revision ID: 7eced9af67f9
Revises: 108cccb69054
Create Date: 2023-11-28 16:23:49.079645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eced9af67f9'
down_revision = '108cccb69054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titleB', sa.String(length=100), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('titleB')

    # ### end Alembic commands ###
