"""empty message

Revision ID: 9adf47765ef3
Revises: a76c98ace71b
Create Date: 2023-11-29 15:47:50.329326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adf47765ef3'
down_revision = 'a76c98ace71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=100), nullable=True),
    sa.Column('blogdetail', sa.Text(), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('add_blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_blog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titleB', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('writer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('blog_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='add_blog_pkey')
    )
    op.drop_table('blog')
    # ### end Alembic commands ###
