"""empty message

Revision ID: a76c98ace71b
Revises: 7eced9af67f9
Create Date: 2023-11-28 16:56:12.229546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76c98ace71b'
down_revision = '7eced9af67f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titleB', sa.String(length=100), nullable=True),
    sa.Column('writer', sa.String(length=100), nullable=True),
    sa.Column('blog_content', sa.Text(), nullable=True),
    sa.Column('phoneNumber', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('writer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('blog', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('titleB', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blog_pkey')
    )
    op.drop_table('add_blog')
    # ### end Alembic commands ###
